# ===================================================================
# Parkend Pro - Configuracion de la Aplicacion Spring Boot
# ===================================================================

spring.application.name=parkend
server.port=8080
server.servlet.context-path=/

# Codificacion y formato UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# Plantillas Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML

# Configuración de registro / logs
logging.level.com.parkend=INFO
logging.level.org.springframework.web=INFO
